export const themeColors = [
  {
    name: 'Amber',
    primary: 'bg-amber-600',
    background: 'bg-amber-100',
    text: 'text-amber-900',
    border: 'border-amber-600',
    isDefault: true,
  },
  {
    name: 'Blue',
    primary: 'bg-blue-800',
    background: 'bg-blue-100',
    text: 'text-blue-900',
    border: 'border-blue-800',
    isDefault: false,
  },
  {
    name: 'Red',
    primary: 'bg-red-700',
    background: 'bg-red-100',
    text: 'text-red-900',
    border: 'border-red-700',
    isDefault: false,
  },
  {
    name: 'Purple',
    primary: 'bg-purple-800',
    background: 'bg-purple-100',
    text: 'text-purple-900',
    border: 'border-purple-800',
    isDefault: false,
  },
  {
    name: 'Green',
    primary: 'bg-green-800',
    background: 'bg-green-100',
    text: 'text-green-900',
    border: 'border-green-800',
    isDefault: false,
  },
  // {
  //   name: "White",
  //   primary: "bg-white",
  //   background: "bg-gray-100",
  //   text: "text-black",
  //   border: "border-gray-300",
  //   isDefault: false,
  // },
  {
    name: 'Light Gray',
    primary: 'bg-[#D6D6D6]',
    background: 'bg-[#f5f5f5]',
    text: 'text-[#333]',
    border: 'border-[#ccc]',
    isDefault: false,
  },
  {
    name: 'Sky Blue',
    primary: 'bg-[#B4E1FF]',
    background: 'bg-[#E6F7FF]',
    text: 'text-[#003A6D]',
    border: 'border-[#7AC6FF]',
    isDefault: false,
  },
  // {
  //   name: "Neon Green",
  //   primary: "bg-[#39FF14]",
  //   background: "bg-[#d4ffcc]",
  //   text: "text-[#0d3b00]",
  //   border: "border-[#39FF14]",
  //   isDefault: false,
  // },
  {
    name: 'Gray',
    primary: 'bg-[#839496]',
    background: 'bg-[#f0f0f0]',
    text: 'text-[#2c3e50]',
    border: 'border-[#839496]',
    isDefault: false,
  },
  {
    name: 'Slate',
    primary: 'bg-[#657B83]',
    background: 'bg-[#eee]',
    text: 'text-[#002b36]',
    border: 'border-[#657B83]',
    isDefault: false,
  },
];
